version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: prueba_user
      POSTGRES_PASSWORD: prueba_pass
      POSTGRES_DB: empleados
    networks:
      - my-network
    ports:
      - '5432:5432'

networks:
  my-network:
    driver: bridge
